### PR TITLE
Consistently use implicit ExecutionContext

### PR DESCRIPTION
**Pull request by mst-appear**
This is a refactoring which I found out when trying to implement chunked BLOB sending. This is independent from chunked BLOB sending though, feel free to merge it if you agree it is an improvment.

### CODE REVIEW

**Comment by mauricio** [comment]
Hi @mst-appear, not using implicits here is intentional, the driver code should avoid using implicits as much as possible and only when it can't be done in a different way, as with the `inTransaction` method.

**Comment by mst-appear** [comment]
Why should the driver avoid implicits?

I think that my refactoring made the code more clean.

**Comment by mauricio** [comment]
Because implicits make the code harder to understand and hide what's happening behind the scenes. The driver code strives to be direct and visible at all times, there's no need to use implicits here were we can just give it the expected parameter directly.

**Comment by mst-appear** [comment]
OK, let's skip it.

**Pull request closed without merging**
